"""init

Revision ID: 402d95ec457c
Revises: 
Create Date: 2026-05-28 13:41:19.016201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '402d95ec457c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.Enum('TEXT_TO_3D', 'IMAGE_TO_3D', name='assettype'), nullable=False),
    sa.Column('status', sa.Enum('GENERATING', 'GENERATED', 'PROCESSING', 'PROCESSED', 'FAILED', name='assetstatus'), nullable=False),
    sa.Column('source_prompt', sa.Text(), nullable=True),
    sa.Column('source_image_path', sa.String(length=500), nullable=True),
    sa.Column('original_model_path', sa.String(length=500), nullable=True),
    sa.Column('processed_model_path', sa.String(length=500), nullable=True),
    sa.Column('glb_path', sa.String(length=500), nullable=True),
    sa.Column('fbx_path', sa.String(length=500), nullable=True),
    sa.Column('obj_path', sa.String(length=500), nullable=True),
    sa.Column('preview_image_path', sa.String(length=500), nullable=True),
    sa.Column('face_count', sa.Integer(), nullable=True),
    sa.Column('vertex_count', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_provider', sa.String(length=50), nullable=True),
    sa.Column('api_task_id', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('page', sa.String(length=200), nullable=True),
    sa.Column('asset_id', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_logs_session_id'), 'user_logs', ['session_id'], unique=False)
    op.create_table('asset_defects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('defect_type', sa.String(length=100), nullable=False),
    sa.Column('level', sa.Enum('MILD', 'MODERATE', 'SEVERE', name='defectlevel'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('region_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('repair_script_path', sa.String(length=500), nullable=True),
    sa.Column('repair_tutorial', sa.Text(), nullable=True),
    sa.Column('auto_repairable', sa.Boolean(), nullable=False),
    sa.Column('repaired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=True),
    sa.Column('task_type', sa.Enum('TEXT_TO_3D', 'IMAGE_TO_3D', 'MODEL_REPAIR', 'SCRIPT_EXECUTION', 'LLM_ANALYSIS', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'RETRYING', name='taskstatus'), nullable=False),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True),
    sa.Column('input_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tasks')
    op.drop_table('asset_defects')
    op.drop_index(op.f('ix_user_logs_session_id'), table_name='user_logs')
    op.drop_table('user_logs')
    op.drop_table('assets')
    # ### end Alembic commands ###
